-- ============================================================
--  내 Todo 앱 — 클라우드(길 B) 백엔드 설정
--  Supabase → SQL Editor → New query 에 이 파일 전체를 붙여넣고 Run
--
--  ★ 이 파일이 건드리는 것은 아래 셋뿐이다.
--      public.todos · public.tags · public.todo_tags
--    어제 제출한 public.results 는 이 파일에서 한 번도 언급되지 않는다.
--    (Ctrl+F 로 'results' 를 찾아보면 이 주석 말고는 없다)
--
--  ★ 먼저 켜야 하는 것
--      Authentication → Sign In / Providers → Anonymous sign-ins  = ON
--    이걸 켜지 않으면 앱이 로그인 단계에서 멈춘다.
-- ============================================================


-- ------------------------------------------------------------
-- 1) 표 세 개
--    오늘 배운 대로 성격이 다른 것끼리 나눈다.
--    user_id 는 '누구의 것'인지를 나타낸다 — 이게 여러 사람이
--    같은 링크를 써도 서로 안 보이게 하는 열쇠다.
-- ------------------------------------------------------------

create table if not exists public.todos (
  id         bigint generated by default as identity primary key,

  -- 로그인한 사람의 id가 자동으로 박힌다. 클라이언트가 보내지 않아도 된다.
  user_id    uuid        not null default auth.uid()
                         references auth.users(id) on delete cascade,

  title      text        not null,
  is_done    boolean     not null default false,
  due_date   date,
  created_at timestamptz not null default now(),

  -- ★ 화면에서 아무 값을 보내도 형식이 다르면 데이터베이스가 거부한다.
  --   어제 results_code_format 제약과 같은 생각이다.
  constraint todos_title_len check (char_length(btrim(title)) between 1 and 200)
);

create table if not exists public.tags (
  id      bigint generated by default as identity primary key,
  user_id uuid   not null default auth.uid()
                 references auth.users(id) on delete cascade,
  name    text   not null,
  color   text   not null default '#1f4e79',

  constraint tags_name_len   check (char_length(btrim(name)) between 1 and 20),
  constraint tags_color_form check (color ~ '^#[0-9a-fA-F]{6}$'),

  -- 태그 이름은 '사람마다' 유일하다.
  -- 내가 '업무'를 쓰든 남이 '업무'를 쓰든 서로 다른 행이다.
  constraint tags_unique_per_user unique (user_id, name)
);

-- 연결 표: N:M 을 '연결 표를 사이에 둔 두 개의 1:N' 으로 푼다
create table if not exists public.todo_tags (
  todo_id bigint not null references public.todos(id) on delete cascade,
  tag_id  bigint not null references public.tags(id)  on delete cascade,
  primary key (todo_id, tag_id)
);


-- ------------------------------------------------------------
-- 2) 색인
--    "색인 넣어줘" 가 아니라 실제 화면의 질문에 맞춰 최소한만 건다.
--      · "내 할 일 중 오늘 마감인 것"      → (user_id, due_date)
--      · "이 할 일에 붙은 태그 다 줘"       → (todo_id)
--      · "이 태그가 붙은 할 일 다 줘"       → (tag_id)
-- ------------------------------------------------------------
create index if not exists todos_user_due_idx     on public.todos     (user_id, due_date);
create index if not exists tags_user_idx          on public.tags      (user_id);
create index if not exists todotags_todo_idx      on public.todo_tags (todo_id);
create index if not exists todotags_tag_idx       on public.todo_tags (tag_id);


-- ------------------------------------------------------------
-- 3) 행 수준 보안(RLS) 켜기
--    이걸 켜지 않으면 공개 키로 누구나 모든 사람의 할 일을
--    읽고 고치고 지울 수 있다.
-- ------------------------------------------------------------
alter table public.todos     enable row level security;
alter table public.tags      enable row level security;
alter table public.todo_tags enable row level security;


-- ------------------------------------------------------------
-- 4) 정책 — "내 것만"
--
--    어제 앱은 '읽기 정책을 아예 만들지 않는' 방법으로 막았다.
--    쓰기만 하고 집계 숫자만 돌려받는 앱이었으니 그게 가능했다.
--
--    Todo 앱은 내가 쓴 것을 내가 다시 읽어야 목록이 뜬다.
--    그래서 읽기를 허용하되 대상을 '내 것'으로 한정한다.
--
--      using      → 읽기·수정·삭제의 '대상'을 고르는 조건
--      with check → 넣거나 고친 결과가 만족해야 하는 조건
--                   (남의 이름으로 넣는 것을 막는다)
-- ------------------------------------------------------------

drop policy if exists "todos: 내 것만" on public.todos;
create policy "todos: 내 것만"
  on public.todos
  for all
  to authenticated
  using      ( auth.uid() = user_id )
  with check ( auth.uid() = user_id );

drop policy if exists "tags: 내 것만" on public.tags;
create policy "tags: 내 것만"
  on public.tags
  for all
  to authenticated
  using      ( auth.uid() = user_id )
  with check ( auth.uid() = user_id );

-- 연결 표에는 user_id 가 없다. 그래서 '부모가 내 것인지'로 판단한다.
drop policy if exists "todo_tags: 내 것만" on public.todo_tags;
create policy "todo_tags: 내 것만"
  on public.todo_tags
  for all
  to authenticated
  using (
    exists (select 1 from public.todos t
             where t.id = todo_tags.todo_id and t.user_id = auth.uid())
  )
  with check (
    exists (select 1 from public.todos t
             where t.id = todo_tags.todo_id and t.user_id = auth.uid())
    and
    exists (select 1 from public.tags g
             where g.id = todo_tags.tag_id  and g.user_id = auth.uid())
  );

-- anon(로그인 안 한 상태) 에게는 어떤 정책도 주지 않는다.
-- → 익명 로그인을 통과하지 않으면 표에 손도 못 댄다.


-- ------------------------------------------------------------
-- 5) 권한을 명시적으로 준다
--    프로젝트 설정에서 자동 노출을 껐더라도 동작하게.
--    anon 에게는 주지 않는다.
-- ------------------------------------------------------------
grant usage on schema public to authenticated;

grant select, insert, update, delete on public.todos     to authenticated;
grant select, insert, update, delete on public.tags      to authenticated;
grant select, insert,         delete on public.todo_tags to authenticated;

grant usage, select on sequence public.todos_id_seq to authenticated;
grant usage, select on sequence public.tags_id_seq  to authenticated;

-- ★ anon 권한은 명시적으로 회수한다 (방어 한 겹 더)
--   verify-rls.mjs 8번 테스트에서 anon 이 HTTP 403 이 아니라
--   'HTTP 200 + 0건' 을 받았다. 프로젝트에 anon 기본 권한이 이미 있어서
--   테이블 접근은 되고 RLS 가 행을 전부 막고 있던 상태였다.
--   결과는 안전하지만, 나중에 실수로 anon 정책이 하나 추가되면
--   그 순간 열린다. 권한 자체를 없애 두면 그 사고를 막는다.
revoke all on public.todos     from anon;
revoke all on public.tags      from anon;
revoke all on public.todo_tags from anon;


-- ------------------------------------------------------------
-- 6) 남용 방어 — 한 사람이 무한히 넣지 못하게
--
--    누구나 익명 계정을 만들 수 있으니, 링크를 뿌리면
--    이론상 아무나 무한히 행을 넣어 무료 한도(DB 500MB)를 채울 수 있다.
--    화면에서 막는 건 친절이고, 여기서 막는 게 방어다.
-- ------------------------------------------------------------
create or replace function public.todos_row_cap()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select count(*) from public.todos where user_id = new.user_id) >= 200 then
    raise exception '할 일은 한 사람당 200개까지입니다';
  end if;
  return new;
end;
$$;

drop trigger if exists todos_cap_trg on public.todos;
create trigger todos_cap_trg
  before insert on public.todos
  for each row execute function public.todos_row_cap();

create or replace function public.tags_row_cap()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select count(*) from public.tags where user_id = new.user_id) >= 50 then
    raise exception '태그는 한 사람당 50개까지입니다';
  end if;
  return new;
end;
$$;

drop trigger if exists tags_cap_trg on public.tags;
create trigger tags_cap_trg
  before insert on public.tags
  for each row execute function public.tags_row_cap();


-- ------------------------------------------------------------
-- 7) 할 일 추가를 '한 번에' 하는 함수
--
--    로컬(길 A)에서는 BEGIN/COMMIT 으로 묶었다.
--      todos 한 줄 + tags 신규분 + todo_tags 여러 줄
--
--    그런데 브라우저에서 REST 로 부르면 요청이 3~4번으로 쪼개진다.
--    중간에 실패하면 태그 없는 할 일이나 주인 없는 연결 줄이 남는다.
--    → 함수로 만들면 본문 전체가 하나의 트랜잭션이 된다.
--      어제 get_stats 를 만든 것과 같은 패턴이다.
--
--    ★ security definer 를 쓰지 않는다 (기본은 security invoker).
--      부른 사람의 권한으로 돌아야 RLS 와 auth.uid() 가 그대로 적용된다.
--      여기서 definer 를 쓰면 RLS 를 우회해 버려 위험하다.
-- ------------------------------------------------------------
create or replace function public.add_todo(
  p_title text,
  p_due   date default null,
  p_tags  text[] default '{}'
)
returns bigint
language plpgsql
set search_path = public
as $$
declare
  v_todo_id bigint;
  v_tag_id  bigint;
  v_name    text;
  v_tags    text[];
begin
  -- user_id 는 열 기본값 auth.uid() 로 자동 채워진다
  insert into public.todos (title, due_date)
  values (btrim(p_title), p_due)
  returning id into v_todo_id;

  -- 태그는 최대 5개까지만 본다.
  -- 슬라이스([1:5])는 '변수'에만 붙일 수 있어서 먼저 변수에 담는다.
  -- coalesce(...)[1:5] 처럼 함수 결과에 바로 붙이면 syntax error 가 난다.
  v_tags := coalesce(p_tags, '{}'::text[]);
  v_tags := v_tags[1:5];

  foreach v_name in array v_tags
  loop
    v_name := btrim(ltrim(btrim(v_name), '#'));
    continue when v_name = '' or char_length(v_name) > 20;

    insert into public.tags (name) values (v_name)
    on conflict (user_id, name) do nothing;

    select id into v_tag_id
      from public.tags
     where user_id = auth.uid() and name = v_name;

    insert into public.todo_tags (todo_id, tag_id)
    values (v_todo_id, v_tag_id)
    on conflict do nothing;
  end loop;

  return v_todo_id;
end;
$$;

revoke all on function public.add_todo(text, date, text[]) from public;
grant execute on function public.add_todo(text, date, text[]) to authenticated;


-- ------------------------------------------------------------
-- 8) 확인용 — 아래를 실행하면 지금 상태를 볼 수 있다
-- ------------------------------------------------------------

-- 표가 잘 생겼나
--   select table_name from information_schema.tables
--    where table_schema='public' and table_name in ('todos','tags','todo_tags');

-- RLS 가 켜졌나  (rowsecurity 가 셋 다 true 여야 한다)
--   select relname, relrowsecurity from pg_class
--    where relname in ('todos','tags','todo_tags');

-- 정책이 들어갔나
--   select tablename, policyname, roles, cmd from pg_policies
--    where tablename in ('todos','tags','todo_tags');

-- 색인을 정말 타는가 ('내 할 일 중 오늘 마감')
--   explain analyze
--   select * from public.todos
--    where user_id = '00000000-0000-0000-0000-000000000000' and due_date = current_date;
--     → 'Index Scan using todos_user_due_idx' 가 보이면 색인을 탄 것이다.

-- 전체 행 수 (SQL Editor 는 관리자 권한이라 다 보인다.
--             브라우저에서는 RLS 때문에 내 것만 보인다)
--   select count(*) from public.todos;
