-- ============================================================
--  AI 협업 성향 테스트 — 결과 집계용 백엔드 설정
--  Supabase → SQL Editor → New query 에 이 파일 전체를 붙여넣고 Run
-- ============================================================


-- ------------------------------------------------------------
-- 1) 결과를 담을 표
-- ------------------------------------------------------------
create table if not exists public.results (
  id          bigint generated by default as identity primary key,
  code        text        not null,
  created_at  timestamptz not null default now(),

  -- ★ 서버에서 다시 검증한다.
  --   16가지 유형 코드 형식(DN·PT·VA·LS 각 한 글자)만 통과시킨다.
  --   화면에서 아무 값을 보내도 형식이 다르면 데이터베이스가 거부한다.
  constraint results_code_format check (code ~ '^[DN][PT][VA][LS]$')
);

create index if not exists results_code_idx on public.results (code);


-- ------------------------------------------------------------
-- 2) 행 수준 보안(RLS) 켜기
--    이걸 켜지 않으면 공개 키로 누구나 데이터를 읽고 고치고 지울 수 있다.
-- ------------------------------------------------------------
alter table public.results enable row level security;


-- ------------------------------------------------------------
-- 3) 정책 — 저장(insert)만 허용한다
--    읽기(select) 정책은 만들지 않는다.
--    → 브라우저에서 원본 결과 목록을 절대 꺼내볼 수 없다.
-- ------------------------------------------------------------
drop policy if exists "insert only valid code" on public.results;

create policy "insert only valid code"
  on public.results
  for insert
  to anon, authenticated
  with check ( code ~ '^[DN][PT][VA][LS]$' );

-- update / delete 정책도 없다 → 남의 결과를 고치거나 지울 수 없다.


-- ------------------------------------------------------------
-- 3-2) 권한을 명시적으로 준다
--     프로젝트 설정에서 "Automatically expose new tables" 를 껐더라도
--     아래 구문 덕분에 저장이 정상 동작한다.
--     select 권한은 주지 않는다 → 원본 행은 여전히 못 읽는다.
-- ------------------------------------------------------------
grant usage  on schema public       to anon, authenticated;
grant insert on table  public.results to anon, authenticated;
grant usage, select on sequence public.results_id_seq to anon, authenticated;


-- ------------------------------------------------------------
-- 4) 집계만 돌려주는 함수
--    security definer 라서 RLS 를 우회해 개수만 계산한다.
--    원본 행은 여전히 나갈 수 없고, 숫자 두 개만 돌아온다.
-- ------------------------------------------------------------
create or replace function public.get_stats(p_code text)
returns json
language sql
security definer
set search_path = public
as $$
  select json_build_object(
    'total', (select count(*) from public.results),
    'count', (select count(*) from public.results where code = p_code)
  );
$$;

revoke all on function public.get_stats(text) from public;
grant execute on function public.get_stats(text) to anon, authenticated;


-- ------------------------------------------------------------
-- 5) 확인용 — 아래를 실행하면 지금 상태를 볼 수 있다
-- ------------------------------------------------------------
-- select public.get_stats('NPVL');
--   → {"total" : 0, "count" : 0}   (아직 아무도 안 했으니 0)

-- select * from public.results;
--   → RLS 때문에 브라우저(anon)에서는 아무 행도 안 보인다.
--     SQL Editor 는 관리자 권한이라 여기서는 보인다.
